### ISSUE TITLE
In contrast to documentation `views` not available in `interface`

### ISSUE THREAD

**Issue by fwolfst** [gavinlaking/vedeu#240]
docs/dsl.md states (besides the change of `'main'` to `:main`):

    interface :main do
      # ...
      views do
        # ...
      end
    end

. This will throw a

```
/home/felix/.rvm/gems/ruby-2.2.2/gems/vedeu-0.6.17/lib/vedeu/dsl/dsl.rb:47:in `method_missing': undefined method `views' for TracktATuiApp:Class (NoMethodError)
	from exe/tracktatui:28:in `block in <class:TracktATuiApp>'
	from /home/felix/.rvm/gems/ruby-2.2.2/gems/vedeu-0.6.17/lib/vedeu/repositories/model.rb:40:in `instance_eval'
	from /home/felix/.rvm/gems/ruby-2.2.2/gems/vedeu-0.6.17/lib/vedeu/repositories/model.rb:40:in `build'
	from /home/felix/.rvm/gems/ruby-2.2.2/gems/vedeu-0.6.17/lib/vedeu/dsl/interface.rb:48:in `interface'
```

replacing `views` with `Vedeu.views` will work, so I guess its an `include` problem.

**Comment by gavinlaking** [comment]
Nice spot! This is actually an error in the documentation which I've now corrected.
