### ISSUE TITLE
DSL Menu example is broken

### ISSUE THREAD

**Issue by gavinlaking** [gavinlaking/vedeu#362]
```ruby
vedeu/lib/vedeu/menus/menu.rb:97:in `items': undefined method `each_with_index' for nil:NilClass (NoMethodError)
	from /home/gavinlaking/Source/vedeu/lib/vedeu/menus/menu.rb:119:in `view'
```

Please run the examples before making releases in future Gav, as these kinds of bugs make you look like a twit.

Gav

**Comment by dymk** [comment]
I was just about to file an issue about this ;) Good to see you've already encountered it, though!

**Comment by pmck91** [comment]
```
error]    undefined method `data' for [nil]:Array
/Users/petermckinney/workspace/vedeu/examples/dsl_menus.rb:219:in `block (2 levels) in show'
/Users/petermckinney/workspace/vedeu/lib/vedeu/repositories/model.rb:40:in `instance_eval'
/Users/petermckinney/workspace/vedeu/lib/vedeu/repositories/model.rb:40:in `build'
/Users/petermckinney/workspace/vedeu/lib/vedeu/dsl/view.rb:62:in `view'
/Users/petermckinney/workspace/vedeu/examples/dsl_menus.rb:218:in `block in show'
/Users/petermckinney/workspace/vedeu/lib/vedeu/repositories/model.rb:40:in `instance_eval'
/Users/petermckinney/workspace/vedeu/lib/vedeu/repositories/model.rb:40:in `build'
/Users/petermckinney/workspace/vedeu/lib/vedeu/dsl/views.rb:151:in `composition'
/Users/petermckinney/workspace/vedeu/lib/vedeu/dsl/views.rb:105:in `renders'
/Users/petermckinney/workspace/vedeu/examples/dsl_menus.rb:217:in `show'
/Users/petermckinney/workspace/vedeu/examples/dsl_menus.rb:91:in `block in initialize'
```

Still seeing errors in this example
